{% set name = "rapidz" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/xpdAcq/rapidz/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: a185a85cb14e426efff64a171ea2fec98037796e68799b9ea09ba2eee0d10bab

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  host:
    - python >=3.9.0
    - pip
  run:
    - python >=3.9.0
    - tornado
    - toolz
    - zict
    - six

test:
  imports:
    - rapidz
    - rapidz.core


about:
  home: https://github.com/xpdAcq/rapidz/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Manage streaming data, optionally with Dask, Pandas and more

  description: |
    Manage streaming data, optionally with Dask and Pandas
  doc_url: https://xpdacq.github.io/rapidz/
  dev_url: https://github.com/xpdAcq/rapidz/

extra:
  recipe-maintainers:
    - st3107
    - sbillinge
