{% set name = "rapidz" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/xpdAcq/rapidz/releases/download/{{ version }}/{{ version }}.tar.gz
  sha256: a313dd46e3dde840bdb44e43a7145645fc7d13da472bfad009e28652f353b1a9

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - tornado
    - toolz
    - zict
    - six

test:
  imports:
    - rapidz
    - rapidz.core


about:
  home: https://github.com/xpdAcq/rapidz/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: "Manage streaming data, optionally with Dask, Pandas and more"

  description: |
    Manage streaming data, optionally with Dask and Pandas
  doc_url: https://xpdacq.github.io/rapidz/
  dev_url: https://github.com/xpdAcq/rapidz/

extra:
  recipe-maintainers:
    - CJ-Wright
