travis:
  secure:
    BINSTAR_TOKEN: bry0c5c/HuMyUtbq3IChWClA7CQsYxcWS1uSKkzYjiIlBgiaKjEjxD/rbIBaxhxigFPMQ3Owe85v5jsHa+kybsQj1Kjh7d8XmYcNJu2YMnXbucJ4N1WBAi1Syc9x82YZUAQtCsY1e7E0X+4ZYctcon+SVjsnW/ZXchdNBB/9rUpnohDi/hsRvexNkqT31pPOL2+At3axbJQp2h/u46PMfdh+vrpqMQMaSnkMeeNgkQagQf6ef7mMse/y1T8J7RD1OXXIxOb20WPCYUCaloNJbSaBNnvGy/+UQhLDO7Mtjx5sABhS5tF/GpaQUa4Mmo+sq7j5+JvBEsqER7Y9fPcMcp+puCu8DnugEieUqcB9UK4DY6/oXk8t4R86iGhC7/uqHZqIFKgiNvWr7njOEIt7RtdmH3NzhkclIFi/bSzR7HF0aWiWMigr4aVAMnVrCNpm0i6/UFZlxwVAmkUIPqCis5CB1uhs6qM6/0ff4jGK1Ezwgmertc1U8f2ZafUgAdTvm3rYkkZTECBw7csvGCTycYbCTbJDbDFCwlh1T2dRIVmmOalqEtzXZ/0DwGjj0x3EEwO1Ks+O2cHbjeloYf3otElxq3rAdxUfw2M8jU89ONviKazY8f7v+UNZyQQ60Q/OCgft/aRDInIMftsX5JHuy+tUYVpvtd0icukU+cqnoWg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
